src/Entity/Media.php
<?php

namespace App\Entity;

use App\Repository\MediaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MediaRepository::class)]
class Media
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $idAPI = null;

    #[ORM\Column(length: 255)]
    private ?string $mediaType = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $is_visible = null;

    #[ORM\Column(length: 255)]
    private ?string $Titre = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateSortie = null;

    #[ORM\Column]
    private ?int $duree = null;

    #[ORM\Column]
    private ?float $note = null;

    #[ORM\OneToMany(mappedBy: 'idMedia', targetEntity: WatchedMedia::class)]
    private Collection $watchedMedias;

    #[ORM\OneToMany(mappedBy: 'idMedia', targetEntity: NextMedia::class)]
    private Collection $nextMedias;

    #[ORM\ManyToOne(inversedBy: 'medias')]
    private ?User $auteur = null;


    public function __construct()
    {
        $this->watchedMedias = new ArrayCollection();
        $this->nextMedias = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdAPI(): ?int
    {
        return $this->idAPI;
    }

    public function setIdAPI(int $idAPI): self
    {
        $this->idAPI = $idAPI;

        return $this;
    }

    public function getMediaType(): ?string
    {
        return $this->mediaType;
    }

    public function setMediaType(string $mediaType): self
    {
        $this->mediaType = $mediaType;

        return $this;
    }

    /**
     * @return Collection<int, WatchedMedia>
     */
    public function getWatchedMedias(): Collection
    {
        return $this->watchedMedias;
    }

    public function addWatchedMedia(WatchedMedia $watchedMedia): self
    {
        if (!$this->watchedMedias->contains($watchedMedia)) {
            $this->watchedMedias->add($watchedMedia);
            $watchedMedia->setIdMedia($this);
        }

        return $this;
    }

    public function removeWatchedMedia(WatchedMedia $watchedMedia): self
    {
        if ($this->watchedMedias->removeElement($watchedMedia)) {
            // set the owning side to null (unless already changed)
            if ($watchedMedia->getIdMedia() === $this) {
                $watchedMedia->setIdMedia(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, NextMedia>
     */
    public function getNextMedias(): Collection
    {
        return $this->nextMedias;
    }

    public function addNextMedia(NextMedia $nextMedia): self
    {
        if (!$this->nextMedias->contains($nextMedia)) {
            $this->nextMedias->add($nextMedia);
            $nextMedia->setIdMedia($this);
        }

        return $this;
    }

    public function removeNextMedia(NextMedia $nextMedia): self
    {
        if ($this->nextMedias->removeElement($nextMedia)) {
            // set the owning side to null (unless already changed)
            if ($nextMedia->getIdMedia() === $this) {
                $nextMedia->setIdMedia(null);
            }
        }

        return $this;
    }
    
    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function isIsVisible(): ?bool
    {
        return $this->is_visible;
    }
    
    public function setIsVisible(?bool $is_visible): self
    {
        $this->is_visible = $is_visible;
        
        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }
    
    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;
        
        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->dateSortie;
    }

    public function setDateSortie(\DateTimeInterface $dateSortie): self
    {
        $this->dateSortie = $dateSortie;
        
        return $this;
    }
    
    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;
        
        return $this;
    }
    
    public function getNote(): ?float
    {
        return $this->note;
    }
    
    public function setNote(float $note): self
    {
        $this->note = $note;
        
        return $this;
    }
    
    public function getAuteur(): ?User
    {
        return $this->auteur;
    }
    
    public function setAuteur(?User $auteur): self
    {
        $this->auteur = $auteur;
        
        return $this;
    }
    
        /**
         *
         * @param User $user
         * @return boolean
         */
        public function isWatchedMedias(User $user): bool
        {
            foreach ($this->watchedMedias as $watchedMedias) {
                if ($watchedMedias->getIdUser() === $user) return true;
            }
            return false;
        }
    
        /**
         *
         * @param User $user
         * @return boolean
         */
        public function isNextMedias(User $user): bool
        {
            foreach ($this->nextMedias as $nextMedias) {
                if ($nextMedias->getIdUser() === $user) return true;
            }
            return false;
        }
}

src/Form/MediaType.php
<?php

namespace App\Form;

use App\Entity\Media;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MediaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('idAPI')
            ->add('titre')
            ->add('mediaType')
            ->add('image')
            ->add('description')
            ->add('note')
            ->add('duree')
            ->add('dateSortie')
            ->add('is_visible')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Media::class,
        ]);
    }
}

src/Controller/MediaController.php
<?php

namespace App\Controller;

use App\Entity\Media;
use App\Entity\NextMedia;
use App\Entity\WatchedMedia;
use App\Form\MediaType;
use App\Repository\MediaRepository;
use App\Repository\NextMediaRepository;
use App\Repository\WatchedMediaRepository;
use App\Service\CallApiService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/media')]
class MediaController extends AbstractController
{
    #[Route('/', name: 'app_media_index', methods: ['GET'])]
    public function index(MediaRepository $mediaRepository): Response
    {
        return $this->render('media/index.html.twig', [
            'media' => $mediaRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_media_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MediaRepository $mediaRepository): Response
    {
        $auteur = $this->getUser();
        $medium = new Media();
        $form = $this->createForm(MediaType::class, $medium);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $medium->setAuteur($auteur);
            $medium->setIsVisible(true);
            $mediaRepository->save($medium, true);

            return $this->redirectToRoute('app_media_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('media/new.html.twig', [
            'medium' => $medium,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_media_show', methods: ['GET'])]
    public function show(Media $medium): Response
    {
        return $this->render('media/show.html.twig', [
            'medium' => $medium,            
        ]);
    }

    #[Route('/{id}/edit', name: 'app_media_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Media $medium, MediaRepository $mediaRepository): Response
    {
        $form = $this->createForm(MediaType::class, $medium);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $mediaRepository->save($medium, true);

            return $this->redirectToRoute('app_media_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('media/edit.html.twig', [
            'medium' => $medium,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_media_delete', methods: ['POST'])]
    public function delete(Request $request, Media $medium, MediaRepository $mediaRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$medium->getId(), $request->request->get('_token'))) {
            $mediaRepository->remove($medium, true);
        }

        return $this->redirectToRoute('app_media_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/watched', name: 'app_media_watched', methods: ['GET', 'POST'])]
    public function mediaWatched(Media $medium, WatchedMediaRepository $watchedMediaRepository): Response
    {
        $user = $this->getUser();
        if (!$user) return $this->redirectToRoute('app_login');

        if ($medium->isWatchedMedias($user)) {
            $signedUp = $watchedMediaRepository->findOneBy([
                'idMedia' => $medium,
                'idUser' => $user
            ]);
            $watchedMediaRepository->remove($signedUp);
            $this->addFlash('Attention', "Ce media n'est plus dans votre liste de medias visionnés.");
            return $this->redirectToRoute('home');
        }

        $newWatched = new WatchedMedia();
        $newWatched->setIdMedia($medium)
            ->setIdUser($user);

        $watchedMediaRepository->save($newWatched);
        $this->addFlash('Succès', "Ce media est désormais dans votre liste de medias visionnés.");

        return $this->redirectToRoute('home');
    }

    #[Route('/{id}/next', name: 'app_media_next', methods: ['GET', 'POST'])]
    public function mediaNext(Media $medium, NextMediaRepository $nextMediaRepository): Response
    {
        $user = $this->getUser();
        if (!$user) return $this->redirectToRoute('app_login');

        if ($medium->isNextMedias($user)) {
            $signedUp = $nextMediaRepository->findOneBy([
                'idMedia' => $medium,
                'idUser' => $user
            ]);
            $nextMediaRepository->remove($signedUp);
            $this->addFlash('Attention', "Ce media n'est plus dans votre liste de medias visionnés.");
            return $this->redirectToRoute('home');
        }

        $newNext = new NextMedia();
        $newNext->setIdMedia($medium)
            ->setIdUser($user);

        $nextMediaRepository->save($newNext);
        $this->addFlash('Succès', "Ce media est désormais dans votre liste de medias visionnés.");

        return $this->redirectToRoute('home');
    }
}

templates/media/_delete_form.html.twig
<form method="post" action="{{ path('app_media_delete', {'id': medium.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ medium.id) }}">
    <button class="btn">Delete</button>
</form>

templates/media/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/media/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Media{% endblock %}

{% block body %}
    <h1>Edit Media</h1>

    {{ include('media/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_media_index') }}">back to list</a>

    {{ include('media/_delete_form.html.twig') }}
{% endblock %}

templates/media/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Media index
{% endblock %}

{% block body %}
	<h1>Media index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>IdAPI</th>
				<th>Titre</th>
				<th>MediaType</th>
				<th>Image</th>
				<th>Description</th>
				<th>Note moyenne</th>
				<th>Durée</th>
				<th>Date de sortie</th>
				<th>Is_visible</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for medium in media %}
				<tr>
					<td>{{ medium.id }}</td>
					<td>{{ medium.idAPI }}</td>
					<td>{{ medium.titre }}</td>
					<td>{{ medium.mediaType }}</td>
					<td>{{ medium.image }}</td>
					<td>{{ medium.description }}</td>
					<td>{{ medium.note }}</td>
					<td>{{ medium.duree }}</td>
					<td>{{ medium.dateSortie }}</td>
					<td>{{ medium.isVisible ? 'Yes' : 'No' }}</td>
					<td>
						<a href="{{ path('app_media_show', {'id': medium.id}) }}">show</a>
						<a href="{{ path('app_media_edit', {'id': medium.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="8">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_media_new') }}">Create new</a>
{% endblock %}

templates/media/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Media{% endblock %}

{% block body %}
    <h1>Ajout d'un nouveau media</h1>

    {{ include('media/_form.html.twig') }}

    <a href="{{ path('app_media_index') }}">back to list</a>
{% endblock %}

templates/media/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Media
{% endblock %}

{% block body %}
	<h1 class="titleInfo">{{medium.titre}}</h1>

	<div class="cardInfo">
		<div class="imgDateRuntime">
			<img src="https://www.themoviedb.org/t/p/w220_and_h330_face/{{medium.image}}" class="cardImgInfo" alt="placeholder">
			<h5>Date de sortie :
				{{medium.dateSortie.format('d/m/Y')}}</h5>
			<h5>Durée :
				{{medium.duree}}min</h5>
		</div>
		<div class="card-body">
			<p class="cardTextInfo">{{medium.description|raw}}</p>
			<p class="card-text">Note moyenne:
				{{ medium.note }}</p>
		</div>
	</div>


	{% if is_granted('ROLE_ADMIN') %}
		<a href="{{ path('app_media_index') }}" class="btn btn-info">Retour à la liste</a>

		<a href="{{ path('app_media_edit', {'id': medium.id})}}" class="btn btn-light">Editer</a>

		{{ include('media/_delete_form.html.twig') }}
	{% endif %}
{% endblock %}